# Generated by Django 5.2.5 on 2025-10-12 00:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_xaf_per_vc', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('deposit_min_xaf', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('deposit_max_xaf', models.DecimalField(decimal_places=2, default=Decimal('10000000.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ORANGE', 'Orange Money'), ('MTN', 'MTN MoMo')], max_length=12)),
                ('phone', models.CharField(max_length=32)),
                ('amount_xaf', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate_xaf_per_vc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coins_vc', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(default='SUCCESS', max_length=16)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
