# Generated by Django 5.2.5 on 2025-08-31 00:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=4)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payout_percent_snapshot', models.PositiveIntegerField(default=80)),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost')], default='OPEN', max_length=6)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='trading_tra_status_b80a43_idx'), models.Index(fields=['user', 'opened_at'], name='trading_tra_user_id_fcf17d_idx')],
            },
        ),
    ]
