# Generated by Django 5.2.5 on 2025-08-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(max_length=12, unique=True)),
                ('payout_percent', models.PositiveIntegerField(default=80)),
                ('volatility', models.CharField(choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High')], default='MID', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
